# As per https://docs.openwebui.com/getting-started/quick-start/:
# docker run -d -p 3000:8080 -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:main
# docker run -d -p 3000:8080 --gpus all -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:cuda
# docker run -d -p 3000:8080 -e WEBUI_AUTH=False -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:main

version: '3'
services:
  openwebui:
    # image: ghcr.io/open-webui/open-webui:0.5.18
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - "7000:8080"
    environment:
      - WEBUI_AUTH=False
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  open-webui: